version: '3.4'
services:
  box: &box
    image: 'model-serving:0.1'
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/model-serving
    environment:
      - FLASK_ENV='development'
    command: /bin/bash
  test:
    <<: *box
    command: "python -m pytest test/"
  app:
    <<: *box
    ports:
      - "5000:5000"
    command: "python run.py"
